### ISSUE TITLE
setReference not working the other way around

### ISSUE THREAD

**Issue by luiz-brandao** [morris/lessql#10]
I have a many to many relationship and I'm using foreign keys in the singular:

```
- orders
- products
- order_has_products

order_has_products.order_id -> orders.id
order_has_products.product_id -> products.id
```

When I use setReference to try to configure this relationship it works only in one sense but not in the other:

```
$db->setReference('order_has_products', 'orders', 'order_id');

// this works
$db->order_has_products([
    'order_id' => 1000,
    'product_id' => 200
])->orders();

// this doesn't work
$db->order(1000)->order_has_productsList()->fetchAll();

// but this works
$db->order(1000)->order_has_productsList()->via('order_id')->fetchAll();
```

Shouldn't it work without `via()` ? Am I doing something wrong or this functionality is not supported?

**Comment by luiz-brandao** [comment]
Seems I should have used `$db->setBackReference()` although it wasn't clear by the example provided by the documentation.

**Comment by morris** [comment]
The confusing part here is that `via` works both ways, whereas references and back references are needed depending on where you start. In your example, you'll need both `setReference` and `setBackReference`: `orders` is back referenced by `order_has_products.order_id` and `order_has_products` references `orders` via `order_id`.

Note however that your db structure does not follow the conventions. If your table names were `order` and `product` instead of their plural forms, _none_ of the schema hints were required (except maybe setPrimary on `order_has_product` because of composite key).

I'll add a note to the docs that table names should really be singular by convention. In any case, thanks for reporting!

**Comment by luiz-brandao** [comment]
Yeah, I understand I wasn't following the standards. It's just that I'm working with an existent database. I guess I just got confused.

**Comment by morris** [comment]
If you have more ideas how to improve the API or the docs somehow, let me know :-)
