### ISSUE TITLE
SQL Server Delimited identifiers

### ISSUE THREAD

**Issue by Kogium** [morris/lessql#19]
Hello there,

Nice Work morris !

Today, meanwhile my integration with PDO instance with SQL Server. i noticed than the delimited identifiers string and method database {Set | Get identifier} are not useful for this case.

So, the right sql statement is  ;
SELECT \* FROM [YourTable] ;
Not
SELECT \* FROM `YourTable` ;

The problem is that we can not use database::quoteIdentifier( CASE ), because we should be use this delimiter "[" in the beggining and this second delimiter "]" at the end.

I know it's a simple interface with PDO. but I find it appropriate to add a Driver Manager Before create statement.

$DriverPDO = $pdo->getAttribute( PDO::ATTR_DRIVER_NAME ) // === 'sqlsrv'

Good continuation !

**Comment by Langmans** [comment]
If LesSQL would use DBAL this wouldn't be an issue :)

**Comment by morris** [comment]
If I remember correctly I could not find any SQL implementation which only supports [] as identifier delimiters. For SQL server, double quotes should be fine: https://technet.microsoft.com/en-us/library/ms176027(v=sql.105).aspx

`$db->setIdentifierDelimiter( '"' )` should work. Otherwise, I'm looking to add [] functionality soon :)

@rubenvincenten That's a design decision - I believe you should be well aware of the SQL implementation you're using to take advantage of all its features. However, if you can find a DBAL that does not take away features from specific SQL implementations, I'll definitely rethink that decision.

In any case, the next version will have a lot of improvements in this area 🍻

**Comment by morris** [comment]
P.S.: Thanks!

**Comment by Kogium** [comment]
i tried to find solutions.

there are not many public API DBAL. i find doctrine framework : https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/DriverManager.php 
But it's look like multiple interface with each database driver. 

i dont now if it's the best way. However you can develop with the structure PDO and use workarounds based on PHP API.

example you accept PDO instances in __construct but you injected controls for the number of results with "INDEX - OFFSET". SQL conventions are not universal.

With INDEX - OFFSET ;
you can use http://php.net/manual/en/pdostatement.fetch.php with Fetching rows with a scrollable cursor 

With prepared statement, you are not obliged to use identifier delimiter : http://php.net/manual/fr/pdo.prepared-statements.php (and use scalar type in php7 for determine the right type need delimiter)

And you right for the identifier delimiter in sqlsrv. I had not seen this possibility :(

you have the choice. Good continuation :)

**Comment by morris** [comment]
As stated before, double quotes should be fine.
