### ISSUE TITLE
Method exists not working

### ISSUE THREAD

**Issue by JDL747** [morris/lessql#34]
Hi,

It seems like the exists method doesn't work, it always returned false !

```
$this->lessQL->begin();

$dbRow = $this->lessQL
    ->createRow('partners_tmp', $tempRow);

   if (!$dbRow->exists()) {
       $dbRow->save();
       $this->lessQL->commit();
   } else {
        continue;
   }

```
And I get the following error :

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: 

Integrity constraint violation: 1062 Duplicate entry 'a.hamdi@reabear.com' for key 'partner_email'' in 

/var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Database.php:662 Stack trace: #0 /var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Database.php(662): PDOStatement->execute() #1
/var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Database.php(571): LessQL\Database->insertDefault('partners_tmp', Array) #2 
/var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Result.php(411): LessQL\Database->insert('partners_tmp', Array, NULL) #3 
/var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Row.php(304): LessQL\Result->insert(Array) #4 
/var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Row.php(345): LessQL\Row->save(false) #5 
/var/www/public/rbplus/views/organisation/OrganisationController.php(133): LessQL\Row->save() #6
/var/www/public/rbplus/views/organisation/OrganisationController.php(100): OrganisationController->populateTempTab in /var/www/public/rbplus/vendor/morris/lessql/src/LessQL/Database.php on line 662
```

Thanks for your helps !

**Comment by Langmans** [comment]
`LessQL\Row::exists` just checks if the `LessQL\Row` object exists in the database, to clarify it further: [it checks if the object has an ID](https://github.com/morris/lessql/blob/master/src/LessQL/Row.php#L530). You also don't have to check if it exists manually since an active record pattern is used, so just run `save` directly since [that will call exists by itself](https://github.com/morris/lessql/blob/master/src/LessQL/Row.php#L285).

And in this case, the error you posted doesn't have anything to do with an existence check. You have a unique constraint for your email column, so you should check if that email is in the database prior to making a new row.

LessQL only supports primary keys, not unique contraints IIRC.
